---
- name: Ensure group "docker" exists
  ansible.builtin.group:
    name: docker
    state: present

- name: Adding user {{ autoreduction_user }} to `docker` group to allow sudoless docker usage
  user: name={{ autoreduction_user }}
        group={{ autoreduction_user }}
        shell=/bin/bash
        password=${password}
        groups=docker
        append=yes

- name: Set run_command depending on deployment stage
  include_vars: "{{ deployment_stage }}.yml"

- name: Pull the docker container to get any updates
  become: yes
  command: docker pull ghcr.io/autoreduction/autoreduce-rest-api:latest

- name: Start the detached Docker container
  become: yes
  command: docker run {{ run_command }} ghcr.io/autoreduction/autoreduce-rest-api:latest
