---

- name: Ensures ~/previous_logs dir exists
  file:
    path: /home/{{ autoreduction_user }}/previous_logs/
    state: directory
    owner: "{{ autoreduction_user }}"
    group: "{{ autoreduction_user }}"

- name: Clear previous Singularity instance logs
  command: mv --backup=numbered /home/{{ autoreduction_user }}/.singularity/instances/logs /home/{{ autoreduction_user }}/previous_logs
  ignore_errors: yes

- name: Start the Singularity instance
  become: yes
  become_user: "{{ autoreduction_user }}"
  command: >
    singularity instance start
    --env AUTOREDUCTION_PRODUCTION=true
    --bind /isis:/isis
    --bind /isis:/archive
    rest-api.sif rest-api
  args:
    chdir: /home/{{ autoreduction_user }}/
